@@host=https://jsonplaceholder.typicode.com
@@dash={{$guid}}

# @name sample1
# @ignoreHeaders .*
GET {{host}}/todos/1?_={{dash}}
content-type: application/json

###

# @title Replay the sample1 request
# @ignoreHeaders .*
GET {{host}}/todos/{{sample1.$.response.body.id}}?_={{dash}}
content-type: application/json

###

# @title POST with JSON body stays as parsed JSON in the snapshot
# @ignoreHeaders .*
POST {{host}}/todos/{{sample1.$.response.body.id}}?_={{dash}}
content-type: application/json

{
  "foo": "bar"
}