@@host=https://jsonplaceholder.typicode.com
@@dash={{$guid}}

# @name sample1
# @ignoreHeaders .*
# @expect $.response.status 200
# @expect $.response.statusText "OK"
GET {{host}}/todos/1?_={{dash}}
content-type: application/json

###

# @name sample2
# @ignoreHeaders .*
# @expectStatus 200
# @expectStatusText "OK"
# @ignore $.response.body.id
# @ignore $.response.body.completed
GET {{host}}/todos/2?_={{dash}}
content-type: application/json
