@@host=https://jsonplaceholder.typicode.com
@@dash={{$guid}}

# @title test global interpolation
# @ignoreHeaders .*
# @expect $.response.status 200
# @expect $.response.statusText "OK"
GET {{host}}/todos/1?_={{dash}}
content-type: application/json

###

# @title test many expects
# @ignoreHeaders .*
# @expect $.response.status 200
# @expect $.response.statusText "OK"
# @ignore $.response.body.id
# @ignore $.response.body.completed
GET {{host}}/todos/2?_={{dash}}
content-type: application/json

###

# @title test the @status meta with both code and text
# @ignoreHeaders .*
# @status 200 "OK"
# @ignore $.response.body.id
# @ignore $.response.body.completed
GET {{host}}/todos/2?_={{dash}}
content-type: application/json

###

# @title test the @status meta with only the code
# @ignoreHeaders .*
# @status 200
# @ignore $.response.body.id
# @ignore $.response.body.completed
GET {{host}}/todos/2?_={{dash}}
content-type: application/json

###

# @title use the @throws meta to ensure that the @status meta works ( status code part )
# @ignoreHeaders .*
# @status 100
# @throws
GET {{host}}/todos/2?_={{dash}}
content-type: application/json

###

# @title use the @throws meta to ensure that the @status meta works ( status text part )
# @ignoreHeaders .*
# @status 200 "foo bar"
# @throws "foo bar"
GET {{host}}/todos/2?_={{dash}}
content-type: application/json
