@@host=https://jsonplaceholder.typicode.com
@@dash={{$guid}}

# @name sample1
# @ignoreHeaders .*
# @expect status 200
# @expect statusText OK
GET {{host}}/todos/1?_={{dash}}
content-type: application/json

###

# @name sample2
# @ignoreHeaders .*
# @expect status 200
# @expect statusText OK
GET {{host}}/todos/2?_={{dash}}
content-type: application/json
